telerik/fiddler-everywhere-docs

user-guide/settings/https.md
Added temporary note related to issue with exporting certificate on Linux (with localization)
=> docs: added Linux installation note

_config.yml
Temporary revert the change from the **master** branch
=> remove contact_support-url

get-started/installation-procedure.md
Related to https://kinvey.atlassian.net/browse/FID-1109
=> docs: internet requirement

introduction.md, support.md
Related to https://kinvey.atlassian.net/browse/FID-1192
=> docs: support page

introduction.md
Related to https://kinvey.atlassian.net/browse/FID-1163
=> docs: Start PRO trial section

introduction.md
=> Typo in introduction.md

_config.yml, use-cases/observe-traffic/capture-web-traffic.md, use-cases/observe-traffic/view-web-session-summary.md
Related to https://kinvey.atlassian.net/browse/FID-1298
=> docs: changing drawer structure

copyright.md, get-started/capture-traffic.md, get-started/collaboration.md, get-started/composer-collections.md, get-started/configuration.md, get-started/create-api-request.md, get-started/inspect-traffic.md, get-started/installation-procedure.md, get-started/mock-server-response.md, get-started/modify-traffic.md, introduction.md, support.md, user-guide/composer.md, user-guide/file-menu.md, user-guide/live-traffic/autoresponder.md, user-guide/live-traffic/inspector-types.md, user-guide/live-traffic/live-traffic.md, user-guide/requests-list.md, user-guide/sessions-list.md, user-guide/settings/connections.md, user-guide/settings/gateway.md, user-guide/settings/https.md, user-guide/settings/privacy.md
The Changes have been made according to the issue: https://kinvey.atlassian.net/browse/FID-1330
=> Styling fiddler documentation

get-started/installation-procedure.md
https://kinvey.atlassian.net/browse/FID-1195
=> [FID-1195] docs: mention the additional .NET Core deps for Windows 7

introduction.md, to_delete.md
Improved wording in the article.
=> docs: minor article updates

knowledge-base/how-to-view-web-session-summary.md
The changes are made with respect to the Issue id: https://kinvey.atlassian.net/browse/FID-1326
=> Use cases articles to knowledge base article 2

user-guide/live-traffic/autoresponder.md
Related to https://kinvey.atlassian.net/browse/FID-1384
=> docs: extend actions section in auto responder

knowledge-base/basic-authentication-with-fiddler-everywhere.md, knowledge-base/capture-and-inspect-web-traffic.md, knowledge-base/configure-android.md, knowledge-base/how-to-install-fiddler-root-certificate-in-firefox-on-linux.md, knowledge-base/how-to-install-fiddler-root-certificate-on-mac-os.md, knowledge-base/how-to-install-fiddler-root-certificate-on-windows.md, knowledge-base/how-to-remove-fiddler-everywhere-certificate-manually.md, knowledge-base/how-to-reset-fiddler-everywhere-settings-to-default.md, knowledge-base/how-to-view-web-session-summary.md, knowledge-base/troubleshoot-mac-proxy-settings.md
https://kinvey.atlassian.net/browse/FID-1325
=> KB article about using Fiddler with Android devices

user-guide/composer.md, user-guide/live-traffic/autoresponder.md, user-guide/live-traffic/inspector-types.md, user-guide/live-traffic/live-traffic.md, user-guide/main-menu.md, user-guide/requests-list.md, user-guide/sessions-list.md, user-guide/settings/connections.md, user-guide/settings/gateway.md, user-guide/settings/https.md, user-guide/settings/privacy.md
https://kinvey.atlassian.net/browse/FID-1483
=> Docs: improving links (related to the new branding and styling)

knowledge-base/configure-android.md
@NickIliev
docs: extend Android article with emulator instructions
Related to https://kinvey.atlassian.net/browse/FID-1526
=> docs: extend Android article with emulator instructions

get-started/installation-procedure.md
Related to https://kinvey.atlassian.net/browse/FID-1498
=> docs: seamless login UX

knowledge-base/redirecting-with-autoresponder.md, user-guide/live-traffic/autoresponder.md
Related to https://kinvey.atlassian.net/browse/FID-1380
=> KB about redirecting traffic

knowledge-base/configure-android.md, knowledge-base/configure-ios.md
Related to https://kinvey.atlassian.net/browse/FID-1549
=> KB about iOS alongside FE

introduction.md, user-guide/live-traffic/live-traffic.md
Redirs for:
https://docs.telerik.com/fiddler-everywhere/license
https://docs.telerik.com/fiddler-everywhere/user-guide/live-traffic/web-sessions/web-sessions-toolbar#filter
=> create redirections for obsolete pages

user-guide/live-traffic/live-traffic.md
https://kinvey.atlassian.net/browse/FID-1578
=> docs: article section improvement about Advanced Filters

knowledge-base/test-fiddler-network-access-on-macos.md, to_delete.md
Related to https://kinvey.atlassian.net/browse/FID-1565
=> KB about troubleshooting the FE's proxy settings

get-started/mobile-traffic/configure-ios.md
remove obsolete information from the articles
=> docs: improve iOS article

release-notes/release-notes.json
=> docs: release notes for FE 1.5.1

user-guide/live-traffic/inspector-types.md
=> fix redirect

get-started/installation-procedure.md, get-started/mobile-traffic/configure-android.md, knowledge-base/basic-authentication-with-fiddler-everywhere.md, knowledge-base/capturing-localhost-traffic.md, knowledge-base/how-to-install-fiddler-root-certificate-on-windows.md, user-guide/requests-list.md, user-guide/settings/connections.md, user-guide/settings/gateway.md, user-guide/settings/https.md
This PR includes suggestions for some of the articles that have relatively high page views and, at the same time, a less than average quality score.
In general, all articles look good, and some of the suggestions are nitpicking that you can choose to ignore :)
I added some comments that try to explain the suggested changes.
=> docs: review docs and suggest changes

knowledge-base/configure-java-app-with-fiddler-everywhere.md
related to https://kinvey.atlassian.net/browse/FID-1906
=> docs: Java app using FE proxy and certificate

introduction.md
The lastest Fiddler Everywhere's upgrade interface and buttons has change.
=> The process of upgrade Pro for free has change.

release-notes/release-notes-insiders.json
> NOTE: Merge when 1.6.0-insiders is uploaded
=> chore: add release notes for 1.6.0-insiders

release-notes/release-notes.json
> NOTE: Merge when 1.6.0 is uploaded
=> [FID-1967] chore: add release notes for 1.6.0

get-started/configuration.md
Related to https://kinvey.atlassian.net/browse/FID-1992
=> create redirect for obsolete article

knowledge-base/how-to-capture-nodejs-traffic.md
Related to https://kinvey.atlassian.net/browse/FID-2042
=> docs: extend the node.js KB

_config.yml, user-guide/settings/privacy.md
related to https://kinvey.atlassian.net/browse/FID-2077
=> update privacy section

knowledge-base/no-net-after-fiddler-exit.md
related to https://kinvey.atlassian.net/browse/FID-2208
=> docs: KB about removing leaked proxy

knowledge-base/capturing-curl-traffic.md, knowledge-base/convert-request-to-curl.md, user-guide/composer.md, user-guide/live-traffic/live-traffic.md
https://kinvey.atlassian.net/browse/FID-2370
=> KB about converting composed request to cURL

_config.yml, get-started/quickstart-linux.md, get-started/traffic/configure-android.md, introduction.md
Still some design layout settings cause problems, specifically when rendering lists.
=> docs: fix lists

user-guide/composer.md
=> docs: improve list styling

traffic/configure-ios.md
ios emulators alongside FE
https://kinvey.atlassian.net/browse/FID-2511
=> update the iOS configuration article

user-guide/live-traffic.md
https://kinvey.atlassian.net/browse/FID-2528
=> minor docs improvment for comment section

get-started/quickstart-linux.md, get-started/quickstart-macos.md, get-started/quickstart-windows.md
Do not merge before the .NET 6.0 is introduced in FE
https://kinvey.atlassian.net/browse/FID-2482
=> docs: update macOS min supported version

installation-and-update/installation-procedure.md, support.md
Related to https://kinvey.atlassian.net/browse/FID-1755
=> docs: SSO option note

copyright.md, traffic/configure-ios.md
… now accesible through the footer
=> unpublish Copyright article 

introduction.md
related to https://kinvey.atlassian.net/browse/FID-2754
=> docs: section about policy-driven installation

user-guide/composer.md
https://kinvey.atlassian.net/browse/FID-2922
=> docs: add headers section

user-guide/overview.md
https://kinvey.atlassian.net/browse/FID-2967
=> docs: minor update of the Overview (note about the copy/paste options)

knowledge-base/how-to-mock-responses.md
Header and cookies were called body
=> Converted to bullets and fixed wrong statements

release-notes/whats-new.json
=> [FID-3295] chore: update whats new for 3.4.0

release-notes/release-notes-insiders.json, release-notes/release-notes.json
add notes for 4.0.0-insiders and 4.0.0
=> Update release notes for 4.0.0 release

release-notes/whats-new.json
https://kinvey.atlassian.net/browse/FID-3704
=> [FID-3704] feat: update whats new for 4.1.0 release

get-started/quickstart-linux.md, get-started/quickstart-macos.md, get-started/quickstart-windows.md
add prerequisites for FE getting started
=> docs: update prerequisites

collaboration.md, knowledge-base/certificate-details.md, user-guide/sessions-list.md
https://kinvey.atlassian.net/browse/FID-3792
=> docs: certificate details in saved sessions

collaboration.md, knowledge-base/fiddler-archives.md, security.md, user-guide/live-traffic.md, user-guide/overview.md
related to https://kinvey.atlassian.net/browse/FID-3966
=> docs: TLS version information in saved sessions

release-notes/whats-new.json
=> chore: update whats new for 4.2.0 release

knowledge-base/capturing-net-traffic.md
related to https://kinvey.atlassian.net/browse/FID-4061
=> docs: article about capturing traffic from NET applications

knowledge-base/troubleshoot-fiddler-not-capturing.md, spell-ignore.txt
review at https://testdocs.telerik.com/fiddler-everywhere/knowledge-base/troubleshoot-fiddler-not-capturing
=> docs: no capture

knowledge-base/capturing-python-traffic.md, spell-ignore.txt
related to https://kinvey.atlassian.net/browse/FID-4089
and to https://kinvey.atlassian.net/browse/FID-3825
=> docs: explanation about capturing Python traffic with Fiddler Everywhere

knowledge-base/basic-authentication-with-fiddler-everywhere.md, knowledge-base/capturing-localhost-traffic.md, knowledge-base/how-to-install-fiddler-root-certificate-on-windows.md, knowledge-base/how-to-mock-responses.md, support.md, traffic/configure-ios.md, user-guide/main-menu.md
https://kinvey.atlassian.net/browse/FID-4126
=> docs: contact support exposure

release-notes/release-notes.json
https://kinvey.atlassian.net/browse/FID-4271
=> [FID-4271] chore: add release notes for 4.3.2

capture-traffic/capture-from-ios.md, capture-traffic/capturing-traffic-from-terminal.md, installation-and-setup/trust-fiddler-ca.md, knowledge-base/capturing-aws-traffic.md, knowledge-base/capturing-python-traffic.md, knowledge-base/configure-fiddler-on-fedora.md, knowledge-base/configure-java-app-with-fiddler-everywhere.md, knowledge-base/how-to-create-pem.md, knowledge-base/how-to-install-fiddler-root-certificate-in-firefox-on-linux.md, knowledge-base/how-to-install-fiddler-root-certificate-on-mac-os.md, knowledge-base/how-to-install-fiddler-root-certificate-on-windows.md, knowledge-base/how-to-remove-fiddler-everywhere-certificate-manually.md, knowledge-base/setup-ca-electron-ubuntu.md, knowledge-base/troubleshoot-certificate-issues.md, knowledge-base/troubleshoot-traffic-capturing.md, spell-ignore.txt, spelling-errors.txt, user-guide/settings/https.md
related to: https://kinvey.atlassian.net/browse/FID-4170
=> docs: update CA file name and Linux instructions

knowledge-base/live-traffic-pane.md, modify-and-filter-traffic/filter-traffic.md
related to https://kinvey.atlassian.net/browse/FID-4165
=> docs: custom column filters

knowledge-base/no-net-after-fiddler-exit.md
related to https://kinvey.atlassian.net/browse/FID-4254
=> docs: leaked proxy article improvment

knowledge-base/troubleshoot-fiddler-not-capturing.md, knowledge-base/troubleshoot-traffic-capturing.md
related to https://kinvey.atlassian.net/browse/FID-4490
=> docs: interaction with third-party proxies

knowledge-base/final-and-non-final-actions.md
related to https://kinvey.atlassian.net/browse/FID-4385
=> docs: add new rule for updating status code

knowledge-base/no-net-after-fiddler-exit.md, knowledge-base/troubleshoot-fiddler-not-capturing.md
related to https://kinvey.atlassian.net/browse/FID-4376
=> Proxy changed: minor article improvments

knowledge-base/how-to-view-web-session-summary.md, knowledge-base/live-traffic-pane.md, knowledge-base/troubleshoot-traffic-capturing.md, modify-and-filter-traffic/filter-traffic.md, user-guide/settings/live-traffic.md
related to https://kinvey.atlassian.net/browse/FID-4162
=> mention the improved custom columns behavour + minor updates

knowledge-base/capturing-traffic-from-mobile-firefox.md, knowledge-base/composer.md, knowledge-base/live-traffic-pane.md
related to https://kinvey.atlassian.net/browse/FID-4625
=> docs: firefox for Android secret settings

capture-traffic/capture-from-remote-pc.md, user-guide/settings/connections.md
relates to https://kinvey.atlassian.net/browse/FID-4717
=> docs: add note about what 'Allow remote devices to connect' actually do

collaboration/sharing-data.md
related to https://kinvey.atlassian.net/browse/FID-4468
=> docs: add additional information about the sharing capabilities

knowledge-base/live-traffic-pane.md
small note related to https://kinvey.atlassian.net/browse/FID-4110
=> docs: remove all note

release-notes/release-notes-insiders.json
https://kinvey.atlassian.net/browse/FID-4837
=> [FID-4837] chore: add release notes for 4.7.1-insiders

knowledge-base/troubleshoot-fiddler-not-capturing.md
related to https://kinvey.atlassian.net/browse/FID-3933
=> docs: add section asbout the unreachable error

capture-traffic/capture-browser-traffic.md, capture-traffic/capture-from-android.md, capture-traffic/capture-from-ios.md, capture-traffic/capture-from-remote-pc.md, capture-traffic/capturing-modes.md, capture-traffic/capturing-traffic-from-terminal.md, installation-and-setup/trust-fiddler-ca.md, knowledge-base/how-to-view-web-session-summary.md, user-guide/settings/https.md
related to https://kinvey.atlassian.net/browse/FID-4259
=> docs: revamped options ins the HTTPS menu

capture-traffic/capture-browser-traffic.md
related to https://kinvey.atlassian.net/browse/FID-4216
=> docs: note about MS Edge as independen browser

installation-and-setup/quickstart-windows.md, knowledge-base/troubleshoot-fiddler-not-capturing.md
related to https://kinvey.atlassian.net/browse/FID-4830
=> update Windows requirments

installation-and-setup/quickstart-linux.md, installation-and-setup/quickstart-macos.md, installation-and-setup/quickstart-windows.md
related to https://kinvey.atlassian.net/browse/FID-5015
=> docs: add access to recaptcha to required access endpoints

knowledge-base/resolve-graphics-issues.md, knowledge-base/troubleshoot-fiddler-not-capturing.md
Related to https://kinvey.atlassian.net/jira/software/c/projects/FID/issues/FID-4969
=> kb and docs section about disabling hard acc

knowledge-base/live-traffic-pane.md
related to https://kinvey.atlassian.net/browse/FID-4807
=> docs: update Copy All Columns

modify-and-filter-traffic/breakpoints.md
related to https://kinvey.atlassian.net/jira/software/c/projects/FID/issues/FID-5351
=> docs: update breakpoint behavior when body is modified

knowledge-base/how-to-capture-websocket-from-safari.md
=> docs: fix MD table

introduction.md
adding links to the Fiddler product pages
related to https://kinvey.atlassian.net/browse/FID-5396
=> docs: add links to product pages

security/tls-version-specifics.md
https://kinvey.atlassian.net/browse/FID-5332
=> docs: note about ciphers

capture-traffic/capturing-modes.md, inspect-traffic/inspector-insights.md
related to https://kinvey.atlassian.net/browse/FID-5403
=> docs: add notes about automatic decoding of WSS messages

collaboration/saving-data.md
related to https://kinvey.atlassian.net/browse/FID-5425
=> docs: add support for non-english languages in file names

knowledge-base/capturing-go-traffic.md
related to https://kinvey.atlassian.net/browse/FID-5551
=> docs: KB about capturing Go localhost traffic

knowledge-base/resolve-graphics-issues.md, knowledge-base/troubleshoot-fiddler-not-capturing.md
related to https://kinvey.atlassian.net/browse/FID-4999
=> hardware acceleration automated solution

introduction.md, knowledge-base/troubleshoot-fiddler-not-capturing.md, support.md
related to https://kinvey.atlassian.net/browse/FID-5513
=> docs: public GH

release-notes/release-notes.json
https://kinvey.atlassian.net/browse/FID-5680
=> [FID-5680] chore: add release notes for 5.7.0

release-notes/release-notes-insiders.json
https://kinvey.atlassian.net/browse/FID-5704
=> [FID-5704] chore: release notes for 5.7.1-insiders

release-notes/release-notes.json
https://kinvey.atlassian.net/browse/FID-5704
=> [FID-5704] chore: release notes for 5.7.1

_config.yml
Replace sheetId with productCode
=> Replace sheetId with productCode

release-notes/release-notes-insiders.json
https://kinvey.atlassian.net/browse/FID-5744
=> [FID-5744] chore: add release notes for 5.9.0-insiders

release-notes/release-notes.json
https://kinvey.atlassian.net/browse/FID-5744
=> [FID-5744] chore: add release notes for 5.9.0

migration.md
related to https://kinvey.atlassian.net/browse/FID-6148
=> new migration flow

capture-traffic/capture-browser-traffic.md, knowledge-base/troubleshoot-fiddler-not-capturing.md
related to https://kinvey.atlassian.net/browse/FID-6097
=> docs: add KB section about ERR_CONNECTION_RESET

security/security-highlights.md
adding a section that highlights that FE is SOC-2 compliant
=> docs: SOC compliance

installation-and-setup/quickstart-windows.md
bump minimum supported version of Win 10
=> docs: add minimum supported Windows version

modify-and-filter-traffic/replaying-traffic.md
fix an issue with the markdown list
=> fix markdown

installation-and-setup/quickstart-linux.md, installation-and-setup/quickstart-macos.md, installation-and-setup/quickstart-windows.md, installation-and-setup/trust-fiddler-ca.md
removing reCaptcha and adding CloudFlare endpoints in requirements
=> docc: update requirments

collaboration/exporting-and-importing.md
related to https://kinvey.atlassian.net/browse/FID-6264
=> docs: improve exports content

inspect-traffic/overview-insights.md
related to https://kinvey.atlassian.net/browse/FID-6558
=> docs: content improvement about timestamps and timings in FE

capture-traffic/capturing-modes.md, introduction.md
related to https://kinvey.atlassian.net/browse/FID-6757
=> docs: add mentions about the Lite plan for FE

knowledge-base/fiddler-archives.md, knowledge-base/live-traffic-pane.md, modify-and-filter-traffic/conditions-and-actions.md
related to https://kinvey.atlassian.net/browse/FID-7082
=> docs: remove obsolete filter condition

capture-traffic/capturing-modes.md, knowledge-base/live-traffic-pane.md
related to https://kinvey.atlassian.net/browse/FID-6992
=> docs: update information about HTTP and TLS version columns

installation-and-setup/offline-mode.md
https://kinvey.atlassian.net/browse/FID-7060
=> improve offline article

_config.yml, fiddler-reporter/features.md, fiddler-reporter/overview.md
rename FIddler Reporter to **Fiddler Everywhere Reporter**
=> docs: rename Fiddler Reporter

inspect-traffic/organizing-traffic.md, knowledge-base/accessing-fiddler-logs.md, knowledge-base/keyboard-shortcuts.md, knowledge-base/requests-list.md
Related to https://kinvey.atlassian.net/browse/FID-7062
=> docs: application shortcuts KB

capture-traffic/capture-from-remote-pc.md, capture-traffic/capture-network-traffic.md, capture-traffic/capturing-modes.md, capture-traffic/capturing-traffic-from-terminal.md, knowledge-base/configure-vpn-with-fiddler.md
related to https://kinvey.atlassian.net/browse/FID-7308
=> docs: improve article about Cisco VPN

capture-traffic/capture-from-android.md, capture-traffic/capture-from-ios.md, capture-traffic/capture-from-remote-pc.md, capture-traffic/capture-system-traffic.md, capture-traffic/capturing-modes.md, fiddler-reporter/features.md, installation-and-setup/quickstart-linux.md, installation-and-setup/quickstart-macos.md, installation-and-setup/quickstart-windows.md, installation-and-setup/trust-fiddler-ca.md, knowledge-base/capturing-python-traffic.md, knowledge-base/how-to-install-fiddler-root-certificate-in-firefox-on-linux.md, knowledge-base/troubleshoot-fiddler-not-capturing.md, user-guide/application-menu.md, user-guide/settings/https.md
rename the options related to the Fiddler CA to CA Certificate
=> docs: CA certificate

user-guide/keyboard-shortcuts.md
related to https://kinvey.atlassian.net/browse/FID-7591
=> docs: add new shortcut

installation-and-setup/advanced-installation/managing-fiddler-extension-instalation.md, installation-and-setup/managed-app-configuration.md
related to https://kinvey.atlassian.net/browse/FID-7682
=> update the bundle ID

installation-and-setup/managed-app-configuration.md
relates to
https://kinvey.atlassian.net/browse/FID-7680  
and to 
https://kinvey.atlassian.net/browse/FID-7684
=> docs: add disable VPN policy and add examples on forcing values

installation-and-setup/quickstart-linux.md, installation-and-setup/quickstart-macos.md, installation-and-setup/quickstart-windows.md
related to https://kinvey.atlassian.net/browse/FID-7757
=> docs: updated SSO links

_config.yml, installation-and-setup/offline-mode.md, installation-and-setup/trust-fiddler-ca.md, knowledge-base/basic-authentication-with-fiddler-everywhere.md, rules-presets/map-traffic/map-localhost.md
part of https://kinvey.atlassian.net/browse/FID-7913
=> docs: SEO optimizations and fixes
